// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnd9uOM60O9OLJl1ySwGVViiLMIfr1ZZU',
    appId: '1:1048306200234:web:29cca49e4f2039ae7a2ad3',
    messagingSenderId: '1048306200234',
    projectId: 'comp4521-b7ca2',
    authDomain: 'comp4521-b7ca2.firebaseapp.com',
    storageBucket: 'comp4521-b7ca2.firebasestorage.app',
    measurementId: 'G-J90RXH63XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhTTGQEy2ks5Be2p6pxXjiSIIsoNcqMY',
    appId: '1:1048306200234:android:dd0b618b752e6cd47a2ad3',
    messagingSenderId: '1048306200234',
    projectId: 'comp4521-b7ca2',
    storageBucket: 'comp4521-b7ca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPqRD8kkshMvr0FjxBfneynIsSniwgKsE',
    appId: '1:1048306200234:ios:3fad6e2280ceb3627a2ad3',
    messagingSenderId: '1048306200234',
    projectId: 'comp4521-b7ca2',
    storageBucket: 'comp4521-b7ca2.firebasestorage.app',
    iosClientId: '1048306200234-uu703k7gfmpoe86lnam6fukh4a5ior4s.apps.googleusercontent.com',
    iosBundleId: 'com.wealthtrack.wealthtrackFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPqRD8kkshMvr0FjxBfneynIsSniwgKsE',
    appId: '1:1048306200234:ios:81c7b92123423d0f7a2ad3',
    messagingSenderId: '1048306200234',
    projectId: 'comp4521-b7ca2',
    storageBucket: 'comp4521-b7ca2.firebasestorage.app',
    iosClientId: '1048306200234-7vnvqi8rlls8gm583ns3kmgqjfthf5rp.apps.googleusercontent.com',
    iosBundleId: 'a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnd9uOM60O9OLJl1ySwGVViiLMIfr1ZZU',
    appId: '1:1048306200234:web:8cc48b5b2b8bd6707a2ad3',
    messagingSenderId: '1048306200234',
    projectId: 'comp4521-b7ca2',
    authDomain: 'comp4521-b7ca2.firebaseapp.com',
    storageBucket: 'comp4521-b7ca2.firebasestorage.app',
    measurementId: 'G-Y8SG5W2T4X',
  );
}
